name: Cross-Platform Testing

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  # First job: Build binaries for different operating systems
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          # Set output filename based on OS
          if [ "${{ matrix.os }}" == "windows" ]; then
            OUTPUT="vet-${{ matrix.os }}.exe"
          else
            OUTPUT="vet-${{ matrix.os }}"
          fi
          
          # Build the binary with specific OS
          go build -o $OUTPUT
          
          # Make binary executable for non-Windows
          if [ "${{ matrix.os }}" != "windows" ]; then
            chmod +x $OUTPUT
          fi

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: vet-${{ matrix.os }}
          path: vet-${{ matrix.os }}*
          retention-days: 1

  # Second job: Test binaries on respective platforms
  test:
    needs: build
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            binary: vet-linux
          - os: darwin
            runner: macos-latest
            binary: vet-darwin
          - os: windows
            runner: windows-latest
            binary: vet-windows.exe

    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: vet-${{ matrix.os }}

      - name: Make binary executable (non-Windows)
        if: matrix.os != 'windows'
        run: chmod +x ${{ matrix.binary }}
        shell: bash

      - name: Test CLI (non-Windows)
        if: matrix.os != 'windows'
        run: |
          # Run basic command
          ./${{ matrix.binary }} version
        shell: bash

      - name: Test CLI (Windows)
        if: matrix.os == 'windows'
        run: |
          # Run basic command
          .\${{ matrix.binary }} version
        shell: powershell